export default {
  name: 'npm-click',
  version: '1.0.1',
  description: 'Comparing NPM (dev)Dependencies',
  repository: {
    type: 'git',
    url: 'https://github.com/manosim/npm-click.git',
  },

  dependencies: {
    '@manosim/reloading': '^0.0.6',
    '@types/react': '=16.0.31',
    '@types/react-dom': '=16.0.3',
    axios: '^0.16.0',
    bootstrap: '^3.3.6',
    browserify: '^9.0.8',
    'chart.js': '^2.7.1',
    'font-awesome': '^4.3.0',
    react: '=16.2.0',
    'react-dom': '=16.2.0',
    'react-chartjs': '=0.6.0',
    typescript: '=1.6.2',
  },
  devDependencies: {
    '@manosim/gitify': '^0.0.1',
    'babel-eslint': '=8.0.3',
    'babel-preset-es2015': '=6.24.1',
    'babel-preset-react': '=6.24.1',
    'babel-preset-stage-0': '=6.24.1',
    eslint: '^4.13.1',
    'eslint-plugin-react': '=7.5.1',
    'redux-logger': '=3.0.6',
    watchify: '=3.9.0',
  },
};
