export default {
  name: 'npm-click',
  version: '1.0.1',
  description: 'Comparing NPM (dev)Dependencies',
  repository: {
    type: 'git',
    url: 'https://github.com/ekonstantinidis/npm-click.git',
  },

  dependencies: {
    '@ekonstantinidis/reloading': '^0.0.6',
    bootstrap: '^3.3.6',
    browserify: '^9.0.8',
    'chart.js': '^1.0.2',
    'font-awesome': '^4.3.0',
    'grunt-gh-pages': '^0.10.0',
    react: '=15.1.0',
    'react-dom': '=15.1.0',
    'react-bootstrap': '^0.21.2',
    'react-chartjs': '^0.6.0',
    'react-dropzone': '^1.0.1',
    'react-router': '^1.0.3',
    reactify: '^1.1.0',
    reflux: '^0.2.7',
    reloading: '0.0.6',
    superagent: '^1.2.0',
    underscore: '^1.8.3',
    watchify: '^3.1.2',
  },

  devDependencies: {
    '@ekonstantinidis/gitify': '^0.0.1',
    grunt: '^1.0.1',
    'grunt-contrib-clean': '^0.7.0',
    'grunt-contrib-copy': '^0.8.2',
    'grunt-contrib-less': '^1.0.1',
    'grunt-contrib-watch': '^0.6.1',
    'jshint-stylish': '^1.0.1',
    jsxhint: '=0.14.0',
    less: '=2.7.1',
  },
};
