export default {
  name: 'npm-click',
  version: '1.0.1',
  description: 'Comparing NPM (dev)Dependencies',
  repository: {
    type: 'git',
    url: 'https://github.com/manosim/npm-click.git',
  },

  dependencies: {
    '@manosim/reloading': '^0.0.6',
    bootstrap: '^3.3.6',
    browserify: '^9.0.8',
    'chart.js': '^2.7.1',
    'font-awesome': '^4.3.0',
    'grunt-gh-pages': '^0.10.0',
    react: '=16.2.0',
    'react-dom': '=16.2.0',
    'react-bootstrap': '^0.21.2',
    'react-chartjs': '^0.6.0',
    'react-dropzone': '^1.0.1',
    'react-router': '^1.0.3',
    reactify: '^1.1.0',
    reflux: '^0.2.7',
    reloading: '0.0.6',
    superagent: '^1.2.0',
    underscore: '^1.8.3',
    watchify: '^3.1.2',
  },
  devDependencies: {
    '@manosim/gitify': '^0.0.1',
    'babel-eslint': '=8.0.3',
    'babel-preset-es2015': '=6.24.1',
    'babel-preset-react': '=6.24.1',
    'babel-preset-stage-0': '=6.24.1',
    eslint: '=4.13.1',
    'eslint-plugin-react': '=7.5.1',
    'lodash.assign': '=4.2.0',
    prettier: '1.9.1',
    'redux-logger': '=3.0.6',
    watchify: '=3.9.0',
  },
};
